sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.5
  - 5.6
  - 7.0

cache:
  - composer
  - $HOME/.composer/cache

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
  - WP_CLI_BIN_DIR=/tmp/wp-cli-phar bash bin/install-package-tests.sh

script: phpunit && WP_CLI_BIN_DIR=/tmp/wp-cli-phar ./vendor/bin/behat
