sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 5.5
- 5.6
- 7.0
cache:
- composer
- "$HOME/.composer/cache"
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
- WP_CLI_BIN_DIR=/tmp/wp-cli-phar bash bin/install-package-tests.sh
script: phpunit && WP_CLI_BIN_DIR=/tmp/wp-cli-phar ./vendor/bin/behat
env:
  global:
    secure: Rhpm3EgbBikvLwCiEYhUivec2Mbq8ddtMoChYFKLa0p70KOpnwzV1wx6RINWvYEoKaZW9UHPR2aQzOPMsT7K1trjFrSdb2dSvnV7B2AKibgnJm9odl0wINoxlW0ioL49BOyqcF2j9wbXk4PKMO5eNFDbB+JgeKXSxdKkYfUxBGi/yyu3WoiMUlkdGO9nBovAMqyLHegvS1vR64FvnlIcrOe/8N1urvHwShkeVsQxHATsIs7oHlxphCsdy4BOU9dvCUZTPPnCqsnG41f1eH93mUGvoH3o1BX30LC5I7WZjxY9D3CekXLu6gyc6itbKxGwWbR+I5ZxuXQK0JMcPKj8q0Ra9RYlmMOh/DzXNULkBsuqi4YXXxKq3zLkwawsierk9EtLIFnmm4m6S770Ig1/KsbJ3QEURHWg9MjbqBc5l6cREOoT7ZAO3AYqeYYULV5+ciZnb99PyoT2T/6HDem8rHrjz4VRhqKLXtqepZbwIa5Jg/9yyeDgPo1L5TpCOLKAp1yvdmxo/0IsFiUavd+rk0Pf1BViKmIm1U6dcla0x5qzhyXGXu2PiJXJAxK/h9cnX2V1SY3MNy00tdCnB398sys2oW34xZudqOqDPa27CDK9oLaUGeRaUBycaAh0++3dGUBWWt7HmYFCjshwCMKm6+ZZZvyo6vs1fWnTnk8hqxg=
