sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 5.6
- 7.0
cache:
- composer
- "$HOME/.composer/cache"
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
- WP_CLI_BIN_DIR=/tmp/wp-cli-phar bash bin/install-package-tests.sh
- composer install
script: ./vendor/bin/phpunit && WP_CLI_BIN_DIR=/tmp/wp-cli-phar ./vendor/bin/behat
env:
  secure: "XlrpBc+FDWQl5vw74d8GQUwpBn7qvgpAtn+D1EchPjXPAKIADocIlh8GI0NhNp4GcQXornUUv8bQPUIs8cM2pp1p3btRYdXgvbNnuxtY/GR4LUlvf0K6nbjeaHOIIofYYEq4x/xSR99TMTeAeoWsUmYkcWzF/ErF38xC1AUr2YmC3LxlHramr0NnRdBrKnf4j3h+UQsNXjcGwxEyYPbWQ1ew+a9ImYMBOR9X7cG0V+sRXcFYCwwvbYAuzH2Ih1wB+OBCvufgbZL8fGK6ydfAUb82X0gx14JNinmRJnYwnC4xzuH88gaHUGHyibTQSQUFn+9v1zUH4v52ZMlA4hfV3tt/njgkH49/P7OP1dpl04xPlNHcvmcGVOUe/ZXq+UBX/HzHPpgy3qJEAR3C4EL0k/RW/J17IeoiG92oGaZU4xq0BAwpbOPEtQtecyFY2f0xeQqHBLpr/mVrIQG6UFiWK7W1e4G6AJdqZiAHkHY8/P2QxLpTS9pCf5VzsBgvPwwfxe9n9s35z7MqyMUt8CZn93SMVS7sOyRNq5AvU0opwGs05Tl9d8xsaZDwfs5BUbbpKInXt+Cr5bvJCPiQiNcctJmdadAT32lRpy7ofA7IM7DXQFS9yA7Kjyz5X97cNTkyprhmrpAk5RGK2FWf+gHPj10rslCvF2NMUXWONylSkV8="
