sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 5.5
- 5.6
- 7.0
cache:
- composer
- "$HOME/.composer/cache"
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
- WP_CLI_BIN_DIR=/tmp/wp-cli-phar bash bin/install-package-tests.sh
script: phpunit && WP_CLI_BIN_DIR=/tmp/wp-cli-phar ./vendor/bin/behat
env:
  secure: Dou16k2Dfuex1doJ5MOZtzdKxEG1BQAAJ06nhpG77+Ibib/yu5v60nhFro2qvCYIEr4GOseE4peFzmi0pSdf7PapalFbC3sDOPhNesfuFqBIhPvI9DVwR++ZjRlQfkdsvVcahMk6Su9Z9ykaSY43UYL7WBFocAV1NUbAizhXxsMvn+p7hZOvmI+gG61PzW7xDfsf0ZS90kNq/aQ+AyoqDZ/Y5rKZmYEa+79NcIm6cBA3CCBgYmgfZ8LtbFhRV3hp9e7A6aYAccTRiGLEif/H3uiLT+S6DrO+E5xCikoB56ir0V+1od41w65Liv2SEv6Pjro2ARo90BKua/ocKafw3b84oDzxWy8PAisJ/rUhmOOhpmle9VqvEuZqTst1uIgXyKc6Unndh/+BJYDDVTDyBZAvkcwF4A6PvBL6esBgQvTk1nKI2erg+VcierMXkANStbVUz1z7IKidCA1/1dOpobCWTUWetAqsxYM8Za6qiH/jijDFA3mDb/e/MwwdPghlHvfuaDC8Bmhjv7Qm2ldLeL1qd4OKFZJxPopaQF0lHHNV/ExQWnhi5RwYmulZ3ZOZfc4COZA91bVcXf/1MGsiIAQVPozXtuAfIKCZW9Ha6ufeApLYhXs0VbMiifzCC2Esgpe7H5mGSt0AvWseaxVhR4bSgpv0ObNrx8+LOTSGUo0=
