sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
php:
- 5.5
- 5.6
- 7.0
cache:
- composer
- "$HOME/.composer/cache"
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
- WP_CLI_BIN_DIR=/tmp/wp-cli-phar bash bin/install-package-tests.sh
script: phpunit && WP_CLI_BIN_DIR=/tmp/wp-cli-phar ./vendor/bin/behat
env:
  global:
  - secure: lul4ich99fKaeeI982KS7PLPL6vgCWi5gdFrAKlaupfG88xY1BLry3eSA04XyJS9uXfOK6ClGNWx+Zx8FTdFjEouEexTN+57FiELjQ++eFaoNCH8eLjpXz+j04fSsqtASfURnrltgXYKRo9y62bMvZ+za6ne64zsnDgrjewzRJYhbL13p92CGq+T7Ug2JI7I100Kjm/KExnhD2UVf7J4l8sTGeG1C799X5N2GV5ThhjBb20AjrgvjkATdZ6tydW9qrOf7oWWP8yLmRwbFkFQAyp3H5HNWR/mcs801Q8MXrE4yb/JEx5Ky9CjMrqEzYTNxDuAe3OFUXeXs1TksPmxRr3Pa02Wp20sDglowu/ABEbYtDdtRhiuV2Mw9a35AU3jhM+dG6isXvueKOyQOGbO7wrXgkLvVSAPd+Vnwu02LppLESHyoEpK9INZjbfOW74ih9Dl0QUtvu7Opi5Br0K/2zZEwiVMA0gD0v3p8uwsZBIPQWMrLDHemTUJBWHnc4PiXleX/8TiiTtCZpEejdCAzRA71s/GXoWIjR8IWIq166VRjfxK4h7t0VbysBY17cOGGQq2LCbofWYLc//dMDOEPzFSad+vaAhduhp2+skyiUiIvn/RTCW/Fms5s+1saY6jqYWI7iuuIMa92az1UiU6zh80qNfUsVrfzEezdM9RIiQ=
  - secure: h6hqIe7trSeN/4EXtpamtbT2WEgaQgJy6K+DXSYwiziR09PHTaZ1ENy3aL5zJiuCJEqsYCSx5463OJwoO7EBzZs90BXU+QlS5LOd9b12lxkadwJ/Gr7biHJ/Pv476DCxtuBjOIBiKfrVALVfDKOXRQcFZxW+fHIswuHjbMptWQeH/HwfbGIIFVNctSAzLdIvGvO4TQ27j8ywVhT2mnH6RKfbYiw2emfz3lhrIEKEkRxbevTtqw3F7cJlHjrrA/ZjLs0Yf+4FP6gcvUXY75IIVz5NBAU7sWB1FgiVSRTZEDrnpBR3dPYGbs3W/Hj4CLeAouvPk4T1yGhkxKNC85yEmCd1UGbI5Fm0g1vR7EjAeN5ff3J1V8BXuMbLcrAQIEusDYxfewhxv+l+Zouyiiz6hsmvCrYl69saSXAdwnpbL5QcXH0vJirDx2jkMfK2YmY7xF5jthhVlUdLO6AyQf5HPP9y/cKAqrakLhj7vth/MaRufRTBUJAtSUjSejMqK4ArC6LrPvaNmfO5pUiZgZFBNOFysul9MDQbye5dA9M+7Goh8OUT8N9UdmienQpgTKp05sWvdCG2ITESzDDvM8AHdeaQFdwHSWVXcpSDRj7y3zKImndqE3fLq73dIQeXUcEFKaoMxZeORD36M7pTZKICYxnwkBUYGCQXfFU+wmVWJs0=
